WebApp/Controllers/BoletaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeManager.Common.Entities;
using TimeManager.BL.Entities;
using TimeManager.WebApp.Http;
using TimeManager.Common.Enums;
using TimeManager.Common.Methods;

namespace TimeManager.WebApp.Controllers
{
    public class BoletaController : Controller
    {
        public ActionResult Index()
        {
            var ListBoleta = BoletaBL.GetList(false);
            return View(ListBoleta);
        }

        public ActionResult Create()
        {
            var ListCliente = ClienteBL.GetList();
            ViewBag.ListCliente = Catalogo.GetSelectListFromCatalog(ListCliente.Select(x => new Catalogo() { Id = x.Id, Nombre = x.Nombre }).ToList());

            var ListProyecto = ProyectoBL.GetList();
            ViewBag.ListProyecto = Catalogo.GetSelectListFromCatalog(ListProyecto.Select(x => new Catalogo() { Id = x.Id, Nombre = x.Nombre }).ToList());

            var ListTiempoInvertido = CatalogoBL.GetList(CatalogoEnum.TiempoInvertido);
            ViewBag.ListTiempoInvertido = Catalogo.GetSelectListFromCatalog(ListTiempoInvertido);

            var ListDepartamento = CatalogoBL.GetList(CatalogoEnum.Departamento);
            ViewBag.Departamento = Catalogo.GetSelectListFromCatalog(ListDepartamento);

            return View();
        }

        [HttpPost]
        public ActionResult Create(Boleta boleta)
        {
            boleta.FechaRegistro = DateTime.Now;
            boleta.EsActivo = true;
            boleta.UsuarioId = 1; // Usuario en sesion

            boleta = BoletaBL.Create(boleta);
            if (boleta.Id > 0)
            {
                return RedirectToAction("Create", "Actividad", new { id = boleta.Id });
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Ocurrió un error al ingresar la boleta");
                return View(boleta);
            }
        }

        public ActionResult Edit(int id)
        {
            Boleta Boleta = BoletaBL.GetById(id);

            if (Boleta != null)
            {
                var ListCliente = ClienteBL.GetList();
                ViewBag.ListCliente = Catalogo.GetSelectListFromCatalog(ListCliente.Select(x => new Catalogo() { Id = x.Id, Nombre = x.Nombre }).ToList());

                var ListProyecto = ProyectoBL.GetList();
                ViewBag.ListProyecto = Catalogo.GetSelectListFromCatalog(ListProyecto.Select(x => new Catalogo() { Id = x.Id, Nombre = x.Nombre }).ToList());

                var ListTiempoInvertido = CatalogoBL.GetList(CatalogoEnum.TiempoInvertido);
                ViewBag.ListTiempoInvertido = Catalogo.GetSelectListFromCatalog(ListTiempoInvertido);

                var ListDepartamento = CatalogoBL.GetList(CatalogoEnum.Departamento);
                ViewBag.Departamento = Catalogo.GetSelectListFromCatalog(ListDepartamento);

                return View(Boleta);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(Boleta boleta)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            bool IsDelete = BoletaBL.Delete(id);

            JsonResponse JsonResponse = new JsonResponse()
            {
                IsSuccess = IsDelete
            };
            return Json(JsonResponse);
        }
    }
}

WebApp/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeManager.Common.Entities;
using TimeManager.BL.Entities;
using TimeManager.Common.Methods;

namespace TimeManager.WebApp.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Boletas(DateTime? del = null, DateTime? hasta = null)
        {
            IEnumerable<Boleta> ListBoleta = null;
            if (del.HasValue && hasta.HasValue)
            {
                ListBoleta = BoletaBL.GetReporteFechas(Converting.DateTimeToSqlString(del.Value), Converting.DateTimeToSqlString(hasta.Value, 1));
            }
            else
            {
                ListBoleta = BoletaBL.GetReporteFechas(Formatting.SqlStringDateFirstDayCurrentMonth(), Formatting.SqlStringDateLastDayCurrentMonth(1));
            }
            return View(ListBoleta);
        }
    }
}

WebApp/Views/Reporte/Boletas.cshtml
@model IEnumerable<TimeManager.Common.Entities.Boleta>

@{
    ViewBag.Title = "Reporte Boletas";
}
@section Breadcrumb{
    <li class="breadcrumb-item">@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
    <li class="breadcrumb-item">@Html.ActionLink("Reportes", "Index", "Reporte")</li>
    <li class="breadcrumb-item active">Boletas</li>
}

<form action="@Url.Action("Boletas")" method="get">
    <div class="row">
        <div class="col-sm-4">
            <div class="form-group">
                <label class="control-label col-md-6">Fecha desde</label>
                <div class="col-sm-12">
                    <input type="date" name="del" value="" class="form-control" required />
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label class="control-label col-md-6">Fecha hasta</label>
                <div class="col-sm-12">
                    <input type="date" name="hasta" value="" class="form-control" required />
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <label class="control-label col-md-6">Filtro</label>
            <div class="col-sm-12">
                <input type="submit" value="Filtrar" class="btn btn-success" />
                <a href="@Url.Action("Boletas")" class="btn btn-danger">Limpiar</a>
            </div>
        </div>
    </div>
    
        
</form>

<div class="row">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroBoleta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaEntrada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraEntrada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaSalida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraSalida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiempoEfectivo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TiempoInvertidoEn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProyectoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClienteId)
            </th>
            <th>Detalle</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroBoleta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaEntrada)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoraEntrada)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaSalida)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoraSalida)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TiempoEfectivo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TiempoInvertidoEn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProyectoId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ClienteId)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>

WebApp/Views/Reporte/Index.cshtml
@section Breadcrumb{
    <li class="breadcrumb-item">@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
    <li class="breadcrumb-item active">Reportes</li>
}

<div class="row">
    <div class="col-sm-12">
        <div class="list-group">
            <a href="@Url.Action("Boletas", "Reporte")" class="list-group-item list-group-item-action">
                Reporte boletas
            </a>
            <a href="@Url.Action("BoletasActividades", "Reporte")" class="list-group-item list-group-item-action">
                Reporte boleta y detalle de actividades
            </a>
        </div>
    </div>
</div>